name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  uv-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Version
        run: echo Version ${{ github.event.release.tag_name }}

      - name: Build
        run: uv build

      - name: Add whl
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./dist/*.whl
